/**
 * Photos réelles de la flotte (public/images/prestige-photos/vehicules/<dossier>/).
 * Fichier généré depuis vehicles.json — ordre du carrousel = ordre ci-dessous, la 1re photo sert de carte.
 * Exclues : photo constructeur du C5 (coffre) et banquette arrière qui n'était pas celle de la Punto.
 */

export type PhotoView =
  | "avant" | "avant-34" | "profil" | "arriere-34" | "arriere"
  | "coffre" | "cargo" | "interieur" | "tableau-de-bord" | "sieges-arriere";

export const FLEET_PHOTOS: Record<string, { src: string; view: PhotoView }[]> = {
  "renault-twingo": [
    { src: "/images/prestige-photos/vehicules/renault-twingo-bleu/renault-twingo-bleu-01-avant-34.webp", view: "avant-34" },
    { src: "/images/prestige-photos/vehicules/renault-twingo-bleu/renault-twingo-bleu-02-arriere-34.webp", view: "arriere-34" },
    { src: "/images/prestige-photos/vehicules/renault-twingo-bleu/renault-twingo-bleu-03-arriere.webp", view: "arriere" },
    { src: "/images/prestige-photos/vehicules/renault-twingo-bleu/renault-twingo-bleu-04-interieur.webp", view: "interieur" },
    { src: "/images/prestige-photos/vehicules/renault-twingo-bleu/renault-twingo-bleu-05-sieges-arriere.webp", view: "sieges-arriere" },
  ],
  "opel-adam": [
    { src: "/images/prestige-photos/vehicules/opel-adam-gris/opel-adam-gris-01-avant-34.webp", view: "avant-34" },
    { src: "/images/prestige-photos/vehicules/opel-adam-gris/opel-adam-gris-02-arriere-34.webp", view: "arriere-34" },
    { src: "/images/prestige-photos/vehicules/opel-adam-gris/opel-adam-gris-03-arriere.webp", view: "arriere" },
    { src: "/images/prestige-photos/vehicules/opel-adam-gris/opel-adam-gris-04-interieur.webp", view: "interieur" },
  ],
  "alfa-romeo-mito": [
    { src: "/images/prestige-photos/vehicules/alfa-romeo-mito-noir/alfa-romeo-mito-noir-01-avant-34.webp", view: "avant-34" },
    { src: "/images/prestige-photos/vehicules/alfa-romeo-mito-noir/alfa-romeo-mito-noir-02-avant.webp", view: "avant" },
    { src: "/images/prestige-photos/vehicules/alfa-romeo-mito-noir/alfa-romeo-mito-noir-03-avant-34.webp", view: "avant-34" },
    { src: "/images/prestige-photos/vehicules/alfa-romeo-mito-noir/alfa-romeo-mito-noir-04-arriere-34.webp", view: "arriere-34" },
    { src: "/images/prestige-photos/vehicules/alfa-romeo-mito-noir/alfa-romeo-mito-noir-05-arriere.webp", view: "arriere" },
    { src: "/images/prestige-photos/vehicules/alfa-romeo-mito-noir/alfa-romeo-mito-noir-06-coffre.webp", view: "coffre" },
    { src: "/images/prestige-photos/vehicules/alfa-romeo-mito-noir/alfa-romeo-mito-noir-07-interieur.webp", view: "interieur" },
    { src: "/images/prestige-photos/vehicules/alfa-romeo-mito-noir/alfa-romeo-mito-noir-08-sieges-arriere.webp", view: "sieges-arriere" },
  ],
  "ford-fiesta": [
    { src: "/images/prestige-photos/vehicules/ford-fiesta-noir/ford-fiesta-noir-01-avant-34.webp", view: "avant-34" },
    { src: "/images/prestige-photos/vehicules/ford-fiesta-noir/ford-fiesta-noir-02-avant.webp", view: "avant" },
    { src: "/images/prestige-photos/vehicules/ford-fiesta-noir/ford-fiesta-noir-03-avant-34.webp", view: "avant-34" },
    { src: "/images/prestige-photos/vehicules/ford-fiesta-noir/ford-fiesta-noir-04-arriere-34.webp", view: "arriere-34" },
    { src: "/images/prestige-photos/vehicules/ford-fiesta-noir/ford-fiesta-noir-05-arriere.webp", view: "arriere" },
    { src: "/images/prestige-photos/vehicules/ford-fiesta-noir/ford-fiesta-noir-06-interieur.webp", view: "interieur" },
    { src: "/images/prestige-photos/vehicules/ford-fiesta-noir/ford-fiesta-noir-07-sieges-arriere.webp", view: "sieges-arriere" },
  ],
  "fiat-punto": [
    { src: "/images/prestige-photos/vehicules/fiat-punto-noir/fiat-punto-noir-01-avant-34.webp", view: "avant-34" },
    { src: "/images/prestige-photos/vehicules/fiat-punto-noir/fiat-punto-noir-02-avant.webp", view: "avant" },
    { src: "/images/prestige-photos/vehicules/fiat-punto-noir/fiat-punto-noir-03-arriere-34.webp", view: "arriere-34" },
    { src: "/images/prestige-photos/vehicules/fiat-punto-noir/fiat-punto-noir-04-arriere-34.webp", view: "arriere-34" },
    { src: "/images/prestige-photos/vehicules/fiat-punto-noir/fiat-punto-noir-05-arriere.webp", view: "arriere" },
    { src: "/images/prestige-photos/vehicules/fiat-punto-noir/fiat-punto-noir-06-interieur.webp", view: "interieur" },
    { src: "/images/prestige-photos/vehicules/fiat-punto-noir/fiat-punto-noir-07-sieges-arriere.webp", view: "sieges-arriere" },
  ],
  "ford-focus": [
    { src: "/images/prestige-photos/vehicules/ford-focus-noir/ford-focus-noir-01-avant-34.webp", view: "avant-34" },
    { src: "/images/prestige-photos/vehicules/ford-focus-noir/ford-focus-noir-02-profil.webp", view: "profil" },
    { src: "/images/prestige-photos/vehicules/ford-focus-noir/ford-focus-noir-03-arriere-34.webp", view: "arriere-34" },
    { src: "/images/prestige-photos/vehicules/ford-focus-noir/ford-focus-noir-04-arriere.webp", view: "arriere" },
    { src: "/images/prestige-photos/vehicules/ford-focus-noir/ford-focus-noir-05-coffre.webp", view: "coffre" },
    { src: "/images/prestige-photos/vehicules/ford-focus-noir/ford-focus-noir-06-interieur.webp", view: "interieur" },
  ],
  "opel-corsa-e": [
    { src: "/images/prestige-photos/vehicules/opel-corsa-rouge/opel-corsa-rouge-01-avant-34.webp", view: "avant-34" },
    { src: "/images/prestige-photos/vehicules/opel-corsa-rouge/opel-corsa-rouge-02-profil.webp", view: "profil" },
    { src: "/images/prestige-photos/vehicules/opel-corsa-rouge/opel-corsa-rouge-03-arriere-34.webp", view: "arriere-34" },
    { src: "/images/prestige-photos/vehicules/opel-corsa-rouge/opel-corsa-rouge-04-arriere.webp", view: "arriere" },
    { src: "/images/prestige-photos/vehicules/opel-corsa-rouge/opel-corsa-rouge-05-coffre.webp", view: "coffre" },
    { src: "/images/prestige-photos/vehicules/opel-corsa-rouge/opel-corsa-rouge-06-interieur.webp", view: "interieur" },
  ],
  "dacia-sandero": [
    { src: "/images/prestige-photos/vehicules/dacia-sandero-bleu/dacia-sandero-bleu-01-avant-34.webp", view: "avant-34" },
    { src: "/images/prestige-photos/vehicules/dacia-sandero-bleu/dacia-sandero-bleu-02-avant.webp", view: "avant" },
    { src: "/images/prestige-photos/vehicules/dacia-sandero-bleu/dacia-sandero-bleu-03-arriere.webp", view: "arriere" },
    { src: "/images/prestige-photos/vehicules/dacia-sandero-bleu/dacia-sandero-bleu-04-coffre.webp", view: "coffre" },
    { src: "/images/prestige-photos/vehicules/dacia-sandero-bleu/dacia-sandero-bleu-05-interieur.webp", view: "interieur" },
  ],
  "citroen-c5-sw": [
    { src: "/images/prestige-photos/vehicules/citroen-c5-break-gris/citroen-c5-break-gris-01-avant-34.webp", view: "avant-34" },
    { src: "/images/prestige-photos/vehicules/citroen-c5-break-gris/citroen-c5-break-gris-02-avant.webp", view: "avant" },
    { src: "/images/prestige-photos/vehicules/citroen-c5-break-gris/citroen-c5-break-gris-03-avant-34.webp", view: "avant-34" },
    { src: "/images/prestige-photos/vehicules/citroen-c5-break-gris/citroen-c5-break-gris-04-arriere-34.webp", view: "arriere-34" },
    { src: "/images/prestige-photos/vehicules/citroen-c5-break-gris/citroen-c5-break-gris-05-arriere-34.webp", view: "arriere-34" },
    { src: "/images/prestige-photos/vehicules/citroen-c5-break-gris/citroen-c5-break-gris-06-arriere.webp", view: "arriere" },
    { src: "/images/prestige-photos/vehicules/citroen-c5-break-gris/citroen-c5-break-gris-07-coffre.webp", view: "coffre" },
    { src: "/images/prestige-photos/vehicules/citroen-c5-break-gris/citroen-c5-break-gris-09-interieur.webp", view: "interieur" },
    { src: "/images/prestige-photos/vehicules/citroen-c5-break-gris/citroen-c5-break-gris-10-sieges-arriere.webp", view: "sieges-arriere" },
  ],
  "peugeot-2008": [
    { src: "/images/prestige-photos/vehicules/peugeot-2008-gris/peugeot-2008-gris-01-avant-34.webp", view: "avant-34" },
    { src: "/images/prestige-photos/vehicules/peugeot-2008-gris/peugeot-2008-gris-02-profil.webp", view: "profil" },
    { src: "/images/prestige-photos/vehicules/peugeot-2008-gris/peugeot-2008-gris-03-arriere-34.webp", view: "arriere-34" },
    { src: "/images/prestige-photos/vehicules/peugeot-2008-gris/peugeot-2008-gris-04-arriere.webp", view: "arriere" },
    { src: "/images/prestige-photos/vehicules/peugeot-2008-gris/peugeot-2008-gris-05-coffre.webp", view: "coffre" },
    { src: "/images/prestige-photos/vehicules/peugeot-2008-gris/peugeot-2008-gris-06-interieur.webp", view: "interieur" },
  ],
  "citroen-c4-picasso": [
    { src: "/images/prestige-photos/vehicules/citroen-c4-picasso-beige/citroen-c4-picasso-beige-01-avant-34.webp", view: "avant-34" },
    { src: "/images/prestige-photos/vehicules/citroen-c4-picasso-beige/citroen-c4-picasso-beige-02-arriere.webp", view: "arriere" },
    { src: "/images/prestige-photos/vehicules/citroen-c4-picasso-beige/citroen-c4-picasso-beige-03-coffre.webp", view: "coffre" },
    { src: "/images/prestige-photos/vehicules/citroen-c4-picasso-beige/citroen-c4-picasso-beige-04-interieur.webp", view: "interieur" },
  ],
  "renault-clio": [
    { src: "/images/prestige-photos/vehicules/renault-clio-gris/renault-clio-gris-01-avant-34.webp", view: "avant-34" },
    { src: "/images/prestige-photos/vehicules/renault-clio-gris/renault-clio-gris-02-avant.webp", view: "avant" },
    { src: "/images/prestige-photos/vehicules/renault-clio-gris/renault-clio-gris-03-arriere-34.webp", view: "arriere-34" },
    { src: "/images/prestige-photos/vehicules/renault-clio-gris/renault-clio-gris-04-arriere.webp", view: "arriere" },
    { src: "/images/prestige-photos/vehicules/renault-clio-gris/renault-clio-gris-05-coffre.webp", view: "coffre" },
    { src: "/images/prestige-photos/vehicules/renault-clio-gris/renault-clio-gris-06-interieur.webp", view: "interieur" },
  ],
  "fiat-500": [
    { src: "/images/prestige-photos/vehicules/fiat-500-gris/fiat-500-gris-01-avant-34.webp", view: "avant-34" },
    { src: "/images/prestige-photos/vehicules/fiat-500-gris/fiat-500-gris-02-arriere-34.webp", view: "arriere-34" },
    { src: "/images/prestige-photos/vehicules/fiat-500-gris/fiat-500-gris-03-coffre.webp", view: "coffre" },
    { src: "/images/prestige-photos/vehicules/fiat-500-gris/fiat-500-gris-04-interieur.webp", view: "interieur" },
  ],
  "opel-astra-plus": [
    { src: "/images/prestige-photos/vehicules/opel-astra-rouge/opel-astra-rouge-01-avant-34.webp", view: "avant-34" },
    { src: "/images/prestige-photos/vehicules/opel-astra-rouge/opel-astra-rouge-02-profil.webp", view: "profil" },
    { src: "/images/prestige-photos/vehicules/opel-astra-rouge/opel-astra-rouge-03-arriere.webp", view: "arriere" },
    { src: "/images/prestige-photos/vehicules/opel-astra-rouge/opel-astra-rouge-04-coffre.webp", view: "coffre" },
    { src: "/images/prestige-photos/vehicules/opel-astra-rouge/opel-astra-rouge-05-interieur.webp", view: "interieur" },
  ],
  "renault-captur": [
    { src: "/images/prestige-photos/vehicules/renault-captur-orange/renault-captur-orange-01-avant.webp", view: "avant" },
    { src: "/images/prestige-photos/vehicules/renault-captur-orange/renault-captur-orange-02-profil.webp", view: "profil" },
    { src: "/images/prestige-photos/vehicules/renault-captur-orange/renault-captur-orange-03-arriere-34.webp", view: "arriere-34" },
    { src: "/images/prestige-photos/vehicules/renault-captur-orange/renault-captur-orange-04-arriere-34.webp", view: "arriere-34" },
    { src: "/images/prestige-photos/vehicules/renault-captur-orange/renault-captur-orange-05-arriere.webp", view: "arriere" },
    { src: "/images/prestige-photos/vehicules/renault-captur-orange/renault-captur-orange-06-interieur.webp", view: "interieur" },
  ],
  "fiat-500l": [
    { src: "/images/prestige-photos/vehicules/fiat-500l-noir/fiat-500l-noir-01-avant.webp", view: "avant" },
    { src: "/images/prestige-photos/vehicules/fiat-500l-noir/fiat-500l-noir-02-profil.webp", view: "profil" },
    { src: "/images/prestige-photos/vehicules/fiat-500l-noir/fiat-500l-noir-03-arriere-34.webp", view: "arriere-34" },
    { src: "/images/prestige-photos/vehicules/fiat-500l-noir/fiat-500l-noir-04-coffre.webp", view: "coffre" },
    { src: "/images/prestige-photos/vehicules/fiat-500l-noir/fiat-500l-noir-05-interieur.webp", view: "interieur" },
  ],
  "citroen-c3": [
    { src: "/images/prestige-photos/vehicules/citroen-c3-rouge/citroen-c3-rouge-02-avant.webp", view: "avant" },
    { src: "/images/prestige-photos/vehicules/citroen-c3-rouge/citroen-c3-rouge-01-profil.webp", view: "profil" },
    { src: "/images/prestige-photos/vehicules/citroen-c3-rouge/citroen-c3-rouge-03-arriere.webp", view: "arriere" },
    { src: "/images/prestige-photos/vehicules/citroen-c3-rouge/citroen-c3-rouge-04-coffre.webp", view: "coffre" },
    { src: "/images/prestige-photos/vehicules/citroen-c3-rouge/citroen-c3-rouge-05-interieur.webp", view: "interieur" },
  ],
  "renault-kangoo-galerie": [
    { src: "/images/prestige-photos/vehicules/renault-kangoo-blanc-2/renault-kangoo-blanc-2-01-avant-34.webp", view: "avant-34" },
    { src: "/images/prestige-photos/vehicules/renault-kangoo-blanc-2/renault-kangoo-blanc-2-02-avant.webp", view: "avant" },
    { src: "/images/prestige-photos/vehicules/renault-kangoo-blanc-2/renault-kangoo-blanc-2-03-avant-34.webp", view: "avant-34" },
    { src: "/images/prestige-photos/vehicules/renault-kangoo-blanc-2/renault-kangoo-blanc-2-04-arriere-34.webp", view: "arriere-34" },
    { src: "/images/prestige-photos/vehicules/renault-kangoo-blanc-2/renault-kangoo-blanc-2-05-arriere-34.webp", view: "arriere-34" },
    { src: "/images/prestige-photos/vehicules/renault-kangoo-blanc-2/renault-kangoo-blanc-2-06-arriere.webp", view: "arriere" },
    { src: "/images/prestige-photos/vehicules/renault-kangoo-blanc-2/renault-kangoo-blanc-2-07-cargo.webp", view: "cargo" },
    { src: "/images/prestige-photos/vehicules/renault-kangoo-blanc-2/renault-kangoo-blanc-2-08-interieur.webp", view: "interieur" },
  ],
  "citroen-nemo": [
    { src: "/images/prestige-photos/vehicules/citroen-nemo-beige/citroen-nemo-beige-01-avant-34.webp", view: "avant-34" },
    { src: "/images/prestige-photos/vehicules/citroen-nemo-beige/citroen-nemo-beige-02-avant.webp", view: "avant" },
    { src: "/images/prestige-photos/vehicules/citroen-nemo-beige/citroen-nemo-beige-03-arriere-34.webp", view: "arriere-34" },
    { src: "/images/prestige-photos/vehicules/citroen-nemo-beige/citroen-nemo-beige-04-arriere-34.webp", view: "arriere-34" },
    { src: "/images/prestige-photos/vehicules/citroen-nemo-beige/citroen-nemo-beige-05-arriere.webp", view: "arriere" },
    { src: "/images/prestige-photos/vehicules/citroen-nemo-beige/citroen-nemo-beige-06-cargo.webp", view: "cargo" },
    { src: "/images/prestige-photos/vehicules/citroen-nemo-beige/citroen-nemo-beige-07-interieur.webp", view: "interieur" },
  ],
  "dacia-dokker": [
    { src: "/images/prestige-photos/vehicules/dacia-dokker-van-gris/dacia-dokker-van-gris-01-avant-34.webp", view: "avant-34" },
    { src: "/images/prestige-photos/vehicules/dacia-dokker-van-gris/dacia-dokker-van-gris-02-avant.webp", view: "avant" },
    { src: "/images/prestige-photos/vehicules/dacia-dokker-van-gris/dacia-dokker-van-gris-03-profil.webp", view: "profil" },
    { src: "/images/prestige-photos/vehicules/dacia-dokker-van-gris/dacia-dokker-van-gris-04-arriere-34.webp", view: "arriere-34" },
    { src: "/images/prestige-photos/vehicules/dacia-dokker-van-gris/dacia-dokker-van-gris-05-cargo.webp", view: "cargo" },
  ],
  "renault-kangoo-echelle-plancher": [
    { src: "/images/prestige-photos/vehicules/renault-kangoo-blanc-1/renault-kangoo-blanc-1-01-avant-34.webp", view: "avant-34" },
    { src: "/images/prestige-photos/vehicules/renault-kangoo-blanc-1/renault-kangoo-blanc-1-02-profil.webp", view: "profil" },
    { src: "/images/prestige-photos/vehicules/renault-kangoo-blanc-1/renault-kangoo-blanc-1-03-arriere.webp", view: "arriere" },
    { src: "/images/prestige-photos/vehicules/renault-kangoo-blanc-1/renault-kangoo-blanc-1-04-cargo.webp", view: "cargo" },
    { src: "/images/prestige-photos/vehicules/renault-kangoo-blanc-1/renault-kangoo-blanc-1-05-cargo.webp", view: "cargo" },
    { src: "/images/prestige-photos/vehicules/renault-kangoo-blanc-1/renault-kangoo-blanc-1-06-cargo.webp", view: "cargo" },
    { src: "/images/prestige-photos/vehicules/renault-kangoo-blanc-1/renault-kangoo-blanc-1-07-interieur.webp", view: "interieur" },
  ],
  "toyota-yaris": [
    { src: "/images/prestige-photos/vehicules/toyota-yaris-gris/toyota-yaris-gris-01-avant-34.webp", view: "avant-34" },
    { src: "/images/prestige-photos/vehicules/toyota-yaris-gris/toyota-yaris-gris-02-avant.webp", view: "avant" },
    { src: "/images/prestige-photos/vehicules/toyota-yaris-gris/toyota-yaris-gris-03-arriere-34.webp", view: "arriere-34" },
    { src: "/images/prestige-photos/vehicules/toyota-yaris-gris/toyota-yaris-gris-04-arriere.webp", view: "arriere" },
    { src: "/images/prestige-photos/vehicules/toyota-yaris-gris/toyota-yaris-gris-05-interieur.webp", view: "interieur" },
    { src: "/images/prestige-photos/vehicules/toyota-yaris-gris/toyota-yaris-gris-06-sieges-arriere.webp", view: "sieges-arriere" },
  ],
  "vw-t-roc": [
    { src: "/images/prestige-photos/vehicules/vw-t-roc-blanc/vw-t-roc-blanc-01-avant.webp", view: "avant" },
    { src: "/images/prestige-photos/vehicules/vw-t-roc-blanc/vw-t-roc-blanc-02-arriere-34.webp", view: "arriere-34" },
    { src: "/images/prestige-photos/vehicules/vw-t-roc-blanc/vw-t-roc-blanc-03-arriere-34.webp", view: "arriere-34" },
    { src: "/images/prestige-photos/vehicules/vw-t-roc-blanc/vw-t-roc-blanc-04-arriere.webp", view: "arriere" },
    { src: "/images/prestige-photos/vehicules/vw-t-roc-blanc/vw-t-roc-blanc-05-interieur.webp", view: "interieur" },
  ],
  "renault-4-e-tech": [
    { src: "/images/prestige-photos/vehicules/renault-4-etech-bleu/renault-4-etech-bleu-01-avant-34.webp", view: "avant-34" },
    { src: "/images/prestige-photos/vehicules/renault-4-etech-bleu/renault-4-etech-bleu-02-avant.webp", view: "avant" },
    { src: "/images/prestige-photos/vehicules/renault-4-etech-bleu/renault-4-etech-bleu-03-arriere.webp", view: "arriere" },
    { src: "/images/prestige-photos/vehicules/renault-4-etech-bleu/renault-4-etech-bleu-04-interieur.webp", view: "interieur" },
    { src: "/images/prestige-photos/vehicules/renault-4-etech-bleu/renault-4-etech-bleu-05-tableau-de-bord.webp", view: "tableau-de-bord" },
    { src: "/images/prestige-photos/vehicules/renault-4-etech-bleu/renault-4-etech-bleu-06-interieur.webp", view: "interieur" },
  ],
  "bmw-x2": [
    { src: "/images/prestige-photos/vehicules/bmw-x2-noir/bmw-x2-noir-01-avant-34.webp", view: "avant-34" },
    { src: "/images/prestige-photos/vehicules/bmw-x2-noir/bmw-x2-noir-02-avant.webp", view: "avant" },
    { src: "/images/prestige-photos/vehicules/bmw-x2-noir/bmw-x2-noir-03-arriere-34.webp", view: "arriere-34" },
    { src: "/images/prestige-photos/vehicules/bmw-x2-noir/bmw-x2-noir-04-arriere-34.webp", view: "arriere-34" },
    { src: "/images/prestige-photos/vehicules/bmw-x2-noir/bmw-x2-noir-05-arriere.webp", view: "arriere" },
    { src: "/images/prestige-photos/vehicules/bmw-x2-noir/bmw-x2-noir-06-tableau-de-bord.webp", view: "tableau-de-bord" },
    { src: "/images/prestige-photos/vehicules/bmw-x2-noir/bmw-x2-noir-07-interieur.webp", view: "interieur" },
  ],
};
